In [57]:
import numpy as np
import pandas as pd

# for multiple output in a cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Pandas Dataframe size adjust
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.options.display.max_columns = 100000000000

In [56]:
pd.DataFrame(np.random.randn(1000,300))

0      1      2      3      4      5      6      7      8      9    \
0   -1.409 -0.346 -0.527  0.229  2.273  0.637  0.878  0.046  0.946 -3.182   
1   -1.311  0.643  0.522  0.152  0.043 -0.168 -1.198 -1.421 -1.434  1.162   
2    0.882 -0.896  0.674 -0.210  0.860 -0.379 -0.553 -0.085 -2.372 -0.890   
3   -0.774  1.408 -0.017 -1.059 -0.851 -0.386 -0.243  0.246 -0.650 -0.262   
4    0.590  0.097  0.164 -0.299  0.277 -0.150  0.504  0.273  0.641 -0.502   
5   -1.196  2.033 -0.474  1.947  1.703 -1.787  0.627 -0.355 -0.702 -1.061   
6    0.141  1.383 -0.450 -1.048 -0.141 -2.304 -0.225  0.686 -1.111  0.259   
7    1.169  1.222  0.586  2.172 -1.068  0.470 -0.632 -0.746  1.434  0.590   
8   -1.392  0.341 -1.112  0.022 -0.595  0.169  1.500  0.323  0.300  0.312   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
991 -1.778  0.202  0.424  0.669 -0.488  0.451  1.146  0.429  0.229  0.297   
992  0.761 -0.517  0.821 -0.520 -1.848  0.625 -0.327  0.125  1.467 -0.292   
993 -2.264 -0.255 -1.148 -0.826  0.208  2.099  0.870 -1.189  1.143  0.000   
994 -0.021  1.508 -1.911 -0.902 -2.508  0.393 -0.422 -0.248 -1.111  0.035   
995 -0.200 -0.981  0.109  1.161  1.837 -1.857 -0.967  0.837 -0.996  0.582   
996  0.619 -0.969 -0.830  1.489 -0.471 -1.237  0.219  0.282  0.570  1.215   
997 -1.004  1.800 -0.003  1.088 -0.707  1.969  0.674 -1.352 -0.438 -1.696   
998  2.162  0.272 -0.918 -1.368  0.882 -0.249 -2.235 -0.352  0.743 -0.743   
999  0.139 -0.442 -2.364 -3.371  1.406 -2.339  0.483 -0.844  0.412  1.323   

       10     11     12     13     14     15     16     17     18     19   \
0    0.213 -1.128 -0.705 -1.455 -0.087 -1.407  2.971  0.225 -1.820  0.855   
1   -1.259 -2.402 -1.416 -0.334 -0.975 -0.542  1.818 -0.228 -0.217 -0.606   
2   -0.148 -2.377 -0.320 -1.427  0.141 -0.902 -0.675  1.727  0.016  0.431   
3    0.914 -0.625  0.356  1.215 -2.592  0.216  1.795 -0.016 -1.122 -0.322   
4   -1.169 -0.966  0.075 -0.442  0.684  1.155 -0.320  0.275 -0.507  0.512   
5   -0.031 -0.060  0.726 -1.181 -1.232  1.394 -0.509 -0.478  0.724 -0.816   
6   -1.662  0.018  0.353 -0.489 -0.168  1.063  0.106  0.556 -0.597 -0.649   
7    2.127  0.235 -1.826 -0.245  0.514  0.132 -1.212 -0.886  0.162  1.245   
8   -0.501  0.253  0.747  1.499 -0.321 -0.056  0.704  0.128  1.924  0.377   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
991 -0.032 -1.257  0.893 -0.147  0.248 -0.404 -0.280 -0.201  0.196 -1.683   
992 -0.355 -1.555 -0.144  0.848 -2.718 -1.321  0.020 -1.365  0.327 -0.141   
993 -1.957 -0.067 -0.173  0.753  1.577 -0.764 -1.175  1.177  0.889  1.577   
994  0.713  0.243 -1.347 -0.474 -1.337  1.637  0.001  0.107 -0.918  0.089   
995 -0.477  0.175 -1.506 -0.895 -0.980  1.477 -0.667 -0.189  1.443  0.503   
996  0.595 -1.461  0.911 -0.996 -0.113  0.913  1.351 -0.344  0.246  0.852   
997 -0.958 -1.169 -0.071 -0.034  1.357 -1.235 -0.804  1.634  0.747  0.740   
998  0.129 -0.398  1.631  1.913 -0.738 -0.237 -2.362 -2.441 -1.328  1.152   
999  0.643  0.552 -0.126  0.560 -0.278  0.270 -0.020 -0.024 -0.352 -2.415   

       20     21     22     23     24     25     26     27     28     29   \
0    0.317  2.427 -0.687  1.660 -0.584 -1.785  0.767  0.018 -1.374  0.555   
1   -0.907 -0.058 -0.813 -0.242 -0.050 -1.016  0.641 -0.370  0.045  0.715   
2    1.511 -0.604  0.372 -1.609 -0.522  0.236 -0.535  0.128  1.463 -1.201   
3   -0.050  0.299  1.179  0.756  0.317 -0.049  1.835 -0.213 -0.662 -2.126   
4   -0.336 -0.447  0.567 -2.373 -0.206 -0.124 -0.502 -2.389 -0.077 -2.067   
5   -0.639 -0.816  1.135 -0.324  0.846 -0.390  1.241 -1.227  0.276  1.935   
6   -1.189  1.079 -0.492  0.731  0.161 -1.272  1.449 -0.615  0.116  0.550   
7   -0.152  0.756  0.147 -1.006  2.559 -1.295  1.423 -1.582  1.087  0.994   
8    0.336 -0.726 -0.690 -0.248  1.314 -0.950  0.110 -1.132 -0.491 -0.195   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
991  1.735 -0.374 -1.338 -0.387 -0.450  0.521  0.693 -0.161 -0.474 -0.148   
9

# `Series` Data type

In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.5.2'

In [4]:
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
type(a)

pandas.core.series.Series

In [6]:
# index setting
s2 = pd.Series(
    [1, 2, 3, 4],
    index=['a', 'b', 'c', 'd']
)
s2

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
s2.head(3)

a    1
b    2
c    3
dtype: int64

In [8]:
# dictionary type
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})
s2.head()

a    1
b    2
c    3
d    4
e    5
dtype: int64

## `nan` function

In [9]:
import numpy as np

In [10]:
np.nan

nan

In [11]:
# dtype: float64 not int due to np.nan
s = pd.Series([10, 0, 1, 1, 2, 3, 4, 5, 6, np.nan])
s

0    10.0
1     0.0
2     1.0
3     1.0
4     2.0
5     3.0
6     4.0
7     5.0
8     6.0
9     NaN
dtype: float64

In [12]:
len(s)
s.shape
s.count()    # not count `nan`

10

(10,)

9

In [13]:
s.unique() # including nan


array([10.,  0.,  1.,  2.,  3.,  4.,  5.,  6., nan])

In [14]:
s.nunique() # except for nan

8

In [15]:
s.value_counts() # except for nan

1.0     2
10.0    1
0.0     1
2.0     1
3.0     1
4.0     1
5.0     1
6.0     1
dtype: int64

## Based on index label, Series operation

In [16]:
s3 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s4 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a']) 

In [17]:
s3 + s4

a    2
b    4
c    6
d    8
dtype: int64

# `DataFrame` Data type

- multiple Series type
    - Series's dict 
        - `{'col1': Series1, 'col2': Series2}`

## DataFrame - creation

In [18]:
s1 = np.arange(1, 6, 1)
s2 = np.arange(6, 11, 1)
s1
s2

array([1, 2, 3, 4, 5])

array([ 6,  7,  8,  9, 10])

In [19]:
df = pd.DataFrame(
    {
        'c1': s1,
        'c2': s2
    }
)
df

c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

In [20]:
# Methond 1 - (Default index and columns would be set)
pd.DataFrame(
    [
        [10,11],
        [10,12]
    ]
)
pd.DataFrame(
    np.array(
        [
            [10, 11],
            [20, 21]
        ]
    )
) 

0   1
0  10  11
1  10  12

0   1
0  10  11
1  20  21

In [21]:
# Method 2
pd.DataFrame(
    [
        pd.Series(np.arange(10, 15)),   
        pd.Series(np.arange(15, 20)),   
    ]
)

pd.DataFrame(
    [
        np.arange(10, 15),
        np.arange(15, 20),
    ]
)

0   1   2   3   4
0  10  11  12  13  14
1  15  16  17  18  19

0   1   2   3   4
0  10  11  12  13  14
1  15  16  17  18  19

In [22]:
# Method 3 - (with column & index names)
pd.DataFrame(
    np.array(
        [
            [10, 11],
            [20, 21]
        ]
    ), 
    columns=['a', 'b'],
    index=['r1', 'r2']
)

    

a   b
r1  10  11
r2  20  21

In [23]:
# Method 4 
s1 = pd.Series(np.arange(1, 6, 1))    
s2 = pd.Series(np.arange(6, 11, 1))   
pd.DataFrame(
    {
        'c1': [1,2,3],    # list, np.array, Series 
        'c2': [4,5,6]
    }
)

c1  c2
0   1   4
1   2   5
2   3   6

In [24]:
# Reference: dictionary의 value -> iterable한 data type(e.g. list, np.array, Series) configuration
pd.DataFrame({'c1': [0], 'c2': [1]})

c1  c2
0   0   1

In [26]:
s1 = pd.Series(np.arange(1, 6, 1), index=['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series(np.arange(6, 11, 1), index=['b', 'c', 'd', 'f', 'g'])
df = pd.DataFrame(
    {
        'c1': s1,
        'c2': s2
    }
)
df

c1    c2
a  1.0   NaN
b  2.0   6.0
c  3.0   7.0
d  4.0   8.0
e  5.0   NaN
f  NaN   9.0
g  NaN  10.0

## DataFrame creation, Series - Index standard sorting

In [27]:
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
s3 = pd.Series(np.arange(12, 15), index=[1, 2, 10])  # this one has index values unlike s1, s2
s1
s2
s3

0    1
1    2
2    3
3    4
4    5
dtype: int64

0     6
1     7
2     8
3     9
4    10
dtype: int64

1     12
2     13
10    14
dtype: int64

In [28]:
df = pd.DataFrame({'c1': s1, 'c2': s2, 'c3': s3}) 
df

c1    c2    c3
0   1.0   6.0   NaN
1   2.0   7.0  12.0
2   3.0   8.0  13.0
3   4.0   9.0   NaN
4   5.0  10.0   NaN
10  NaN   NaN  14.0

## DataFram - to add column 

In [29]:
my_dict['a'] = 1

NameError: name 'my_dict' is not defined

In [30]:
df['c4'] = pd.Series([1,2,3,4], index=[0, 1, 2, 10])

In [31]:
df

c1    c2    c3   c4
0   1.0   6.0   NaN  1.0
1   2.0   7.0  12.0  2.0
2   3.0   8.0  13.0  3.0
3   4.0   9.0   NaN  NaN
4   5.0  10.0   NaN  NaN
10  NaN   NaN  14.0  4.0

## Reindexing

- New index label -> "index-value" mapping


### new index ("index-value" mapping broken)

In [58]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [59]:
s.index = ['a', 'b', 'c', 'd', 'e']
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

### `set_index()`

In [60]:
df

c1     c2     c3    c4
0  1.000  6.000    NaN 1.000
1  2.000  7.000 12.000 2.000
2  3.000  8.000 13.000 3.000
3  4.000  9.000    NaN   NaN
4  5.000 10.000    NaN   NaN
10   NaN    NaN 14.000 4.000

In [61]:
df['c5'] = pd.Series([1,2,3,4,5,6], index=[0,1,2,3,4,10])
df

c1     c2     c3    c4  c5
0  1.000  6.000    NaN 1.000   1
1  2.000  7.000 12.000 2.000   2
2  3.000  8.000 13.000 3.000   3
3  4.000  9.000    NaN   NaN   4
4  5.000 10.000    NaN   NaN   5
10   NaN    NaN 14.000 4.000   6

In [62]:
df.set_index("c5")

c1     c2     c3    c4
c5                          
1  1.000  6.000    NaN 1.000
2  2.000  7.000 12.000 2.000
3  3.000  8.000 13.000 3.000
4  4.000  9.000    NaN   NaN
5  5.000 10.000    NaN   NaN
6    NaN    NaN 14.000 4.000

### Reindex

In [63]:
s2 = s.reindex(
    ['a', 'c', 'e', 'g']
)
s2

a   1.000
c   3.000
e   5.000
g     NaN
dtype: float64

In [64]:
# Copied
s2['a'] = 0
s2

a   0.000
c   3.000
e   5.000
g     NaN
dtype: float64

In [65]:
# Do not use this
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])
s2 = pd.Series([3, 4, 5], index=['0', '1', '2'])
s1
s2

0    0
1    1
2    2
dtype: int64

0    3
1    4
2    5
dtype: int64

In [66]:
s1 + s2

0   NaN
1   NaN
2   NaN
0   NaN
1   NaN
2   NaN
dtype: float64

In [67]:
s1.index

Int64Index([0, 1, 2], dtype='int64')

In [68]:
s2 = s2.reindex(s1.index)
s2

0   NaN
1   NaN
2   NaN
dtype: float64

In [69]:
# How to fix? Method 1
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])
s2 = pd.Series([3, 4, 5], index=['0', '1', '2'])

In [70]:
s2.index = s2.index.astype(int)

In [71]:
s2

0    3
1    4
2    5
dtype: int64

In [72]:
s2.index

Int64Index([0, 1, 2], dtype='int64')

In [73]:
s1 + s2

0    3
1    5
2    7
dtype: int64

In [74]:
# How to fix it? Method 2
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])
s2 = pd.Series([3, 4, 5], index=['0', '1', '2'])

In [75]:
s1.index = ['a', 'b', 'c']
s2.index = ['a', 'b', 'c']

In [76]:
s1 + s2

a    3
b    5
c    7
dtype: int64

#### `reindex()` useful Arguments

- `fill_value`

In [77]:
s2 = s.copy()
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [78]:
s2.reindex(['a', 'f'])

a   1.000
f     NaN
dtype: float64

In [79]:
s2.reindex(['a', 'f'], fill_value=0)  # fill 0 insteand of Nan

a    1
f    0
dtype: int64

- `method`

In [80]:
s3 = pd.Series(['red', 'green', 'blue'], index=[0, 3, 5])
s3

0      red
3    green
5     blue
dtype: object

In [81]:
s3.reindex(np.arange(0,7))

0      red
1      NaN
2      NaN
3    green
4      NaN
5     blue
6      NaN
dtype: object

In [83]:
# based on previous one, fill in NaN
s3.reindex(np.arange(0,7), method='ffill')

0      red
1      red
2      red
3    green
4    green
5     blue
6     blue
dtype: object